### ISSUE TITLE
Testing epic

### ISSUE THREAD

**Issue by Perksey** [dotnet/Silk.NET#412]
# Development
## Tests
- [ ] [In Progress] GLFW tests - @HurricanKai 
- [ ] [In Progress] Maths tests - See maths/testing
    - [ ] Scalar.Abs<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Acos<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Acosh<T>(T x) -> T - _unclaimed_
    - [x] Scalar.Add<T>(T left, T right) -> T - @HurricanKai 
    - [ ] Scalar.As<TFrom, TTo>(TFrom val) -> TTo - _unclaimed_
    - [ ] Scalar.Asin<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Asinh<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Atan2<T>(T y, T x) -> T - _unclaimed_
    - [ ] Scalar.Atan<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Atanh<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Cbrt<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Ceiling<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Cos<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Cosh<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Divide<T>(T left, T right) -> T - _unclaimed_
    - [ ] Scalar.Equal<T>(T left, T right) -> bool - _unclaimed_
    - [ ] Scalar.Exp<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Floor<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.GreaterThan<T>(T left, T right) -> bool - _unclaimed_
    - [ ] Scalar.GreaterThanOrEqual<T>(T left, T right) -> bool - _unclaimed_
    - [ ] Scalar.IEEERemainder<T>(T x, T y) -> T - _unclaimed_
    - [ ] Scalar.IsFinite<T>(T f) -> bool - _unclaimed_
    - [ ] Scalar.IsInfinity<T>(T f) -> bool - _unclaimed_
    - [ ] Scalar.IsNaN<T>(T f) -> bool - _unclaimed_
    - [ ] Scalar.IsNegative<T>(T f) -> bool - _unclaimed_
    - [ ] Scalar.IsNegativeInfinity<T>(T f) -> bool - _unclaimed_
    - [ ] Scalar.IsNormal<T>(T f) -> bool - _unclaimed_
    - [ ] Scalar.IsPositiveInfinity<T>(T f) -> bool - _unclaimed_
    - [ ] Scalar.IsSubnormal<T>(T f) -> bool - _unclaimed_
    - [ ] Scalar.LessThan<T>(T left, T right) -> bool - _unclaimed_
    - [ ] Scalar.LessThanOrEqual<T>(T left, T right) -> bool - _unclaimed_
    - [ ] Scalar.Log10<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Log<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Log<T>(T x, T y) -> T - _unclaimed_
    - [ ] Scalar.Max<T>(T x, T y) -> T - _unclaimed_
    - [ ] Scalar.Min<T>(T x, T y) -> T - _unclaimed_
    - [ ] Scalar.Multiply<T>(T left, T right) -> T - _unclaimed_
    - [ ] Scalar.Negate<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.NotEqual<T>(T left, T right) -> bool - _unclaimed_
    - [ ] Scalar.Pow<T>(T x, T y) -> T - _unclaimed_
    - [ ] Scalar.Reciprocal<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Round<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Round<T>(T x, int digits) -> T - _unclaimed_
    - [ ] Scalar.Round<T>(T x, int digits, System.MidpointRounding mode) -> T - _unclaimed_
    - [ ] Scalar.Round<T>(T x, System.MidpointRounding mode) -> T - _unclaimed_
    - [ ] Scalar.Sign<T>(T x) -> int - _unclaimed_
    - [ ] Scalar.Sin<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Sinh<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Sqrt<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Subtract<T>(T left, T right) -> T - _unclaimed_
    - [ ] Scalar.Tan<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Tanh<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Truncate<T>(T x) -> T - _unclaimed_
    - [ ] _More to be added_
- [ ] [Not Started] SilkTouch tests - _unclaimed_

## Benchmarks
- [ ] [In Progress] Math benchmarks- See maths/testing
    - [ ] Scalar.Abs<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Acos<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Acosh<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Add<T>(T left, T right) -> T - _unclaimed_
    - [ ] Scalar.As<TFrom, TTo>(TFrom val) -> TTo - _unclaimed_
    - [ ] Scalar.Asin<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Asinh<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Atan2<T>(T y, T x) -> T - _unclaimed_
    - [ ] Scalar.Atan<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Atanh<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Cbrt<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Ceiling<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Cos<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Cosh<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Divide<T>(T left, T right) -> T - _unclaimed_
    - [ ] Scalar.Equal<T>(T left, T right) -> bool - _unclaimed_
    - [ ] Scalar.Exp<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Floor<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.GreaterThan<T>(T left, T right) -> bool - _unclaimed_
    - [ ] Scalar.GreaterThanOrEqual<T>(T left, T right) -> bool - _unclaimed_
    - [ ] Scalar.IEEERemainder<T>(T x, T y) -> T - _unclaimed_
    - [ ] Scalar.IsFinite<T>(T f) -> bool - _unclaimed_
    - [ ] Scalar.IsInfinity<T>(T f) -> bool - _unclaimed_
    - [ ] Scalar.IsNaN<T>(T f) -> bool - _unclaimed_
    - [ ] Scalar.IsNegative<T>(T f) -> bool - _unclaimed_
    - [ ] Scalar.IsNegativeInfinity<T>(T f) -> bool - _unclaimed_
    - [ ] Scalar.IsNormal<T>(T f) -> bool - _unclaimed_
    - [ ] Scalar.IsPositiveInfinity<T>(T f) -> bool - _unclaimed_
    - [ ] Scalar.IsSubnormal<T>(T f) -> bool - _unclaimed_
    - [ ] Scalar.LessThan<T>(T left, T right) -> bool - _unclaimed_
    - [ ] Scalar.LessThanOrEqual<T>(T left, T right) -> bool - _unclaimed_
    - [ ] Scalar.Log10<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Log<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Log<T>(T x, T y) -> T - _unclaimed_
    - [ ] Scalar.Max<T>(T x, T y) -> T - _unclaimed_
    - [ ] Scalar.Min<T>(T x, T y) -> T - _unclaimed_
    - [ ] Scalar.Multiply<T>(T left, T right) -> T - _unclaimed_
    - [ ] Scalar.Negate<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.NotEqual<T>(T left, T right) -> bool - _unclaimed_
    - [ ] Scalar.Pow<T>(T x, T y) -> T - _unclaimed_
    - [ ] Scalar.Reciprocal<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Round<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Round<T>(T x, int digits) -> T - _unclaimed_
    - [ ] Scalar.Round<T>(T x, int digits, System.MidpointRounding mode) -> T - _unclaimed_
    - [ ] Scalar.Round<T>(T x, System.MidpointRounding mode) -> T - _unclaimed_
    - [ ] Scalar.Sign<T>(T x) -> int - _unclaimed_
    - [ ] Scalar.Sin<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Sinh<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Sqrt<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Subtract<T>(T left, T right) -> T - _unclaimed_
    - [ ] Scalar.Tan<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Tanh<T>(T x) -> T - _unclaimed_
    - [ ] Scalar.Truncate<T>(T x) -> T - _unclaimed_
    - [ ] _More to be added_

_More to be added_

# Milestones
_To be added_

Dates are a loose estimate and are subject to change.

**Comment by Perksey** [comment]
This issue is obsolete as of 3.0.
