### ISSUE TITLE
SIMD Math tracking issue

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/Silk.NET#666]
Tracks implementation of the [**SIMD Math Proposal**](https://github.com/WhiteBlackGoose/Silk.NET/blob/patch-2/documentation/proposals/Proposal%20-%20Vectorization%20-%20SIMD.md).

It is being implemented in the `feature/math-simd`.

## Main tasks

#665 
- [ ] `Create`
- [ ] `WithElement`
- [ ] `GetElement`
- [ ] `Load`
- [ ] `Add`
- [ ] `Subtract`
- [ ] `Multiply`
- [ ] `Divide`
- [ ] `Abs`
- [ ] Constants

# ???
- [ ] `AllBitsSet`
- [ ] `Acos`
- [ ] `Acosh`

## TODOs

- [ ] `Divide` for integers to be done in a more efficient way [link](https://stackoverflow.com/questions/16822757/sse-integer-division)
- [ ] `Multiply` for bytes to be done in a more efficient way [link](https://stackoverflow.com/questions/8193601/sse-multiplication-16-x-uint8-t)

**Comment by WhiteBlackGoose** [comment]
## Ideas

### Sinh / Cosh
Those two have similar formulas:
```
(e^x + e^-x) / 2
(e^x - e^-x) / 2
```
So we can have Sinh/Cosh method

Speaking of implementation, we have
```cs
var ex = Simd.Exp(x);
var exm = Simd.Reciprocal(ex);
var multiplier = Simd.Create(0.5);
var sinh = Simd.Multiply(Simd.Subtract(ex, exm), multiplier);
var cosh = Simd.Multiply(Simd.Add(ex, exm), multiplier);
return (sinh, cosh);
```

**Comment by HurricanKai** [comment]
Should verify that for Store (and other void returning methods) the nested method trick actually works.

**Comment by WhiteBlackGoose** [comment]
128 bit [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8B6YgAgBkBLMGAO1xgBMyMJWALGMgOgDkAogBUyAMQgBXOk2wYqEOmSlMYUMgu7Qy+aN2wBzWDHz0MuHgFgAUKTJCuvQSPHLZ8xQBsa9Rrk5U/ADMqD242MgBPSSVpVU5uAFkASREvWgYYSytrAGIVYLpuAEEmADcAZSSEgBFc/KpCsnLygWtrAAEAJgBGDoAGMnbungAlKTkTHgBhCHwABxDVctVS71wAbn7B4bG6CcykvagG3BoNraHR8apJw4xjhjOeAA0ADiRN7Kt2gcvd/Z4dwepzA5iKUHwnzaVjo2BMuDm2FoTRCAGt+MIeAlZBxcNYAN7WMjEwYAZm2SBiuGwgW4iKgcmwHkGnRR+CY3U6ryJJMJVhJArIpHIAB5cBJ8PhsFAIgA+HmCoW2AAKqkC0Hwfg40qYAHdpfAkbRQlBZMwmmxYOpFJzXnBgFQMGRSjAwJbzArBcKyCLiOLJdK5Z6BQBtBIwDAcCBMJLzDwACnDkejsbmHgA8nM5AowfpDDBcKcXYcvHQGvoyIQyEmozG45nswweEU87BC1QXQ2blQAF5uBQASgAusGSSHytqoHMKNhgFc9jdMgApR0AcXoqho8YwETmMAggXjuCjDIHw9HxPHk+ns/nAJXGHXhWOYG3u/3h8CHggsjPI/5ipkFe0o3nO/yLjwD5Ppur47nuB7xkwkjAKEf4XmSFKDCgFq6CKQiyvGQgAFRkCouByLCjZoGQABqrqWraeGymQuCSFAtADmQupcFaIggDEUqwvozDoXygGCgAQhEGAwIhBYUf2dDUaxEjsTAA7rOJAroaGNYpnGiYRrWqYZlm7i5vm7bFnQpblpW1ZGfpaZdjmzatgWRYwF2+C9op54AVpmHtNhUkyYRJFkQpVG0fR0CMfhLFsRxOm8ilipUIEZBvvBh5CJxAC8+WsO+CHANJ6kDmlgp8jkGVkCUFRVLUAWBYBdXxg15Q3EwgK4OUEhzHM0AyUwlUta11VVRNnXdTw5SWrJ8ZlTJRGcZFDSKdR8Z0W6cVciKy0wLKnHxhAwAAFb0ZxKlqRpU2AQAvrk9BMBluR1c0rTjRNJLteUjCdL1/WDcNzBjT9gFiRDWn/TAgPzbo8ZLeVq2kfJG3RdtsVQIxh3HVlZ2XW611JepnzQ4KT1WDkL1vd9gVU+J93EuUoWyetlHuMppN3fTlMTVVYaOXWaaGcmIumY2Fltp5JYNHZVZ6RLLlNi2lmed5vmNv5E1DJSwVNGz4Vo+RGNczFu04/tCU3clfMClDEPtXBH6EQVRUuwhuCHWezNkDVdWdU1fsCu1M3skDA1DQyYMh6l9vQ+HPUI7ASPeyja3o5zChbTtDH7enMn46dF1XYlqkceTFMklTNPSHTtWZZ9cfEn9AORyDMejS3/s9wKsPwwtaeHajHObVled7a8Yp4ydhNl7bZM97XtOBH7jOAX7ACqdzdEgcmm9nSnl7dVcMwLCeXkrJli8Z9Zma5asyx2MBy2WdAVorwsmSr0seS/ms+za3/LrPeWEyA7z2HvY2Y9oqTyttPG2PMqqOx+s7EquV3bFRyvGCQx5hq+0vpNamgcyiVBqD3MOZDZpJD6lHUG3ciHiVQdXEkSc5pD1wfghko8s7jyxpbRieCTwYGLvPYmJ9K7L2evXNeJCm4tEoZleMA8O7RxGuDVhvcmGtVUSnRawjhq8MPvw+BQjuGiLnqXCRi9eZaLICvWR690J+13vvWB5tbFny0g9C+E0hbixvtfe+Us3Lqxfm/BWDlAkhPMmE5+nYzI+SAe4HWrU9bgLcTAvhcDsbxWYrYlBft0E4LymQQq2DXYWMIRTAOmUg4UJ0elZR7DaHA3UbHJpxD7ECnYfotOIjjFRXNgI/O08LFiOsRgEmFcl5dIFI416cjG5NEUfM36yjVFtPoV3TRrCWFaL0ZwixQyzY5wnnkguIjJlE2mZIuZ9jFl0wphvRU287ikk6AfYZ5yvFVV8a1QWwTRbAslnEp+/9rK2Q/vZUFv94mQq8kkrWqSQHpLAQbSBGBPnZJMbkwR1sCnIKIQcwKJTXZlIqZ7Q8EgGjTL2T9Op9UyHB3Wa3Fp1CI7bM7honupLq59M4bSvYpyj650udPYVliCZTJmafaR1NV7vQUV9exbc4ZqIYQy2pfcSRHMRrgulorTESpFFKm5C8ebeJeTIpZzi+auL2DijxvyrX/L8a1AJd8QXf1iY/dyVlX42XljCr+MTnIP1VgGjWyKUmDjRYFDJBsPlfOIibH5x8zGEvudqyGxTlHUrduUj2GD4x0pqdDJlDTmpqo5RUGhdCeWdPsfyimgqDVGsznikZWbp50otTYt1bKHG2obh9NZtaspbMbR0xhLbdUs3bv0stIqu0ZvFQSvtewB13L+cOp5cibUOq6Vi1A3yznHz3RNAFgUgW+p9eGsF/rwlQpDZ/aJ3qn1RpfUiiYKL41VSTdhU9KBcXrotmMpiOaildPJQhSlJacESG/B/CtEMq0ssaZOjqnKerctnbm9DC7mX1ojsu5DCh9DGsxr2s1KH9A7rlVI/do7lnjtVVo9VgN8Nar5cR/VqdcH0eoz201FGP6MZzda6GB77VMy6XcM9LrL1DuvR6wKXqnIJjhZGv+gbImho/Vp+FELA2AL8gmrSQGyCKdA2m5T1FaNINmYR7p0M4OYOLZUhC9G0OMuVSR8hNbON1q6lymdvHh2tsTrhjhBrhNrovRuyD9HJNXq0bJ+RqyOOsK45q3ZfHh39yXZwhL6aksXM3SKVLVjblMYeRl1jcnN5dK6h/UI56xVSfdYCohmmJa32M7phF+ng3v3fTp0JpmY1/rjXQNJiaMXYTa/oDr9mcnmyc0SlzMGKYeaLVS0tX4fz0r9hhxqWGQtZVaRFgrUXiPtsE8d2QInzmjKniKZ70qS51e6yxxVTisvN2HXlnjd351Fb1SVg1X3XvH3ewgz735ZBpdU41gHdqumvMFH7aoyEOsOb+2p3r/jQWDeVsN6bESxtRMm+C6NADY0WcA0tsgeOJAoVkut7t5ytvQZJfmrKhaEPecPEhDnqFXPMIC9WpR13Ytg95fdyHxJHuLXF5zuHyWPsa9CKjlz0mIaZZWcD7D072mRYhz0qHGrl265gFryrkH7f6/lf9uumOj3yYpumSMqhOvj3SwzO9j7yc/0pwz1943YX3q/Xpmb3Y5sLas6z33PEwMVb54UgXJ6GA0kyAAdWODJLesIvD6EKEwEUW2CKE73f89C2OqZUyAA===)

256 bit [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8B6YgAgBkBLMGAO1xgBMyMJWALGMgOgDkAogBUyAMQgBXOk2wYqEOmSlMYUMgu7Qy+aN2wBzWDHz0MuHgFgAUKTJCuvQSPHLZ8xQBsa9Rrk5U/ADMqD242MgBPSSVpVU5uAFkASREvWgYYSytrAGIVYLpuAGUigVz8qkKyAEEmADcipISAEWtrAAEAJgBGDoAGMnbungAlKTkTHgBhCHwABxDVItU671wAbn7B4bG6CcykvahK3BoN3KpAshKyq3aBodHxqknDjGOGM54ADQAOJE2Vhy9CYlwuV1qDSarTuDx2z1eRxOX2qUHwgOB0jB2SsdGwJlwc2wtGuIQA1vxhDwErIOLhrABvaxkFmDADM2yQMVw2EC3CJUDk2A8g06pPwTE6AFYkMzWUyrKylWRSOQADy4CT4fDYKARAB8cuVKtsAAVVIFoPg/BxdUwAO66+DE2ihKCyZjXNiwdSKaVIODAKgYMh1GBgb3mI3K1VkNXETXa3UG6NKgDaCRgGA4ECYSXmHgAFJns7n83MPAB5OZyBTmar6QwwXCnMOHLx0Sr6MiEMglnN5gvV2sMHgNpstqhh4cvKgALzcCgAlABdVOstNFW1QOYUbDAJ57F6ZABSwYA4vRVDRCxgInMYBBAoXcDnBUvV+uWZvt7v94f9h4M8MEvQpjjAW970fZ9Ag8CBZA/NdFWNMgf11P8D12QDgNA68ILvB8n0LJhJGAUJEK/dlOUGFAvV0NUhH1QshAAKjIFRcDkPERzQMgADVw29f0GP1MhcEkKBaCXMh7S4H0RBAGIdTxfRmEohUUOVAAhCIMBgYjmy4xc6F48SJEkmAl3WTSlUo9N+zLAtiyzAdyyrGt3HrRtYEnNs6A7Lsez7FzHIrGc6zHbzm1bGAZ3wedjM/ZCbOo9paJ0vTmLYjijJ4/jBOgYTGLEiSpLs+VyuNS4yEgwjnyEaSAF5GtYKCiOAXTLKXSrlQVHJquqPjvh6zTqsLao6gQToeCSXAigkOY5mgPSmG65KUpQjSNu2iapp4IpvX0wsOr0ljpJyypjN4wsBIjQqZTVE6YH1aTCwgYAACtBOksyLKskaUIAX1yEFsW2pVgfW2yoY2ooMv0i7uPcUzSsswFtsB7aeozELBwrZzSzx9yRy8icYvbSpAt7ByifC0dxx8mK4oSkcku2oYuTS654ay9jDMuvLbqEh7it+sqYeNLbwbIMaCOg5impauWiNwJ6PwBlk+oGoaNeVMbdum2b5sW5bmDW6XJd1zSDf2w7CxfJ6zr5ziBeRmqhfupANSel6aver6Ix+1H/ol8HIcxUFAl1yHNN1gBVN5uiQAyXaRhQUfMqT0Y2zGNuxmm3IJ1yhw8iKGeiqcYApzs6G7ancbcunScZyvmYXVmkPZpOaLIBO9iT3nEau/K7qgIrRLFyyeql8HZba+rFdaurCwkV9lvV0PNK1iEdc3jb9cmw25oWpbBTNq2Kr36WbYO3R7dXt8MCdoe8pugqx4eh/lt9t7Pu+krM5owviycOoMo5X2VDHFCutE7Jxfm7SeIcMZYwgTjQmhcC4lxJpFMmldq5U2CugrBnkcEt2nB5eK7d3Bsw2hzHusDB78zTiZEewsvai2DtPXWc9l4NTIM1Je8s17vnNhbbeNRd4Wz1lccah8ZrHxNmfVawCyAzykUqG+dsXyP2fkw4eb9R7CWERgH+/t/6IOzuosgoCsTgKkVA408c3hsk6CnXKCDg6WJsrnFK+cG5OUwWFUu9Moq+Srv5SmtcgqBOJiQ8uYS26JU7rQ7uXM+4YBcYw1Ow8PYf3YRPThEC1H7xkcrBe/ClbzxXpUDAG8pHiMGsNCBo0ZE2yNifU2yjmmbRURouRt9YD3xqbo7Jr9cnCQkDU0xf9A4AL+l4+xINbHR0ojAvYmT4HpzmVnHqPibJ+KIfjGJTdSEVz8gFKJ9dDmxLLqEpmFCWbUOSSlOhXNnGuNYs7dxWzxkiwKYA0RKVikpR4fLPhAiymFhqXUsR4IJFNKsSyA+e12mKJWoC9RwL1GaLvlCvYIzvksIMWwtUUzXpmNmRYlRNjI4rNDk4vYqA3Guy2VSiBezY6oJiUXUKNyQm4POZEuuhDi5BOwfE+5ExHnLmeTZV5tF0lMs+Zslhvz8nbKnkU7hpSqngsqcvCQcFa4wulg0yRiLkVH2NqfdFKisVSJxYMleRr9AEpZUStVapDUKH0NMgOtSNVIMRTSsGFsHHKjWRgJlKqM7zN2Sg7aaDRVFmOcE5uZzwkXOFam8VdzW4PKoTKnq8qyBvCVdlPRgt37j0DVw7pSKdW8MXpCl1JrwZmoRRa1pcjUU2vPvW3qvTWSOqOi6t1zDrqepdX68xnjqVLNpQO8N0MpFFC7KEZlE7A0LKBgmjaSbeU8tpmm05YT8GXJFbyk5Er81SsLXQGhLzUm0TXbXDdyrK1u09RwgFdapGgqInqwRRFYLwVqRi7aHaVGWvkdazpEHYUDutv0rRoHZDjv0Z6tDJjyUzIDWyxF1iF2hulsu1kutmikQ3TG7d8a85cv8UcxjfL01noiTXbNzHr15vIXepJxbn1kEoxIMi+kP2jK/dWv5tatUDoA+UiFVSSIifIghoFcLGnQe7SihRfaumEftRbEd9tlOiYw2MqTXtTOhBnZSudSHWQhrsWG1ZA7KzZlUJu4eBGc4HOTUexuJ6b2Co49ErjQWeOxQLfxiBJb3NySyYS3i37/l/T/RbOODBeSZAAOrHD0pl4UVB9CFCYGqFLTEaNst2ZRcNkNIZAA)

64 bit [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8B6YgAgBkBLMGAO1xgBMyMJWALGMgOgDkAogBUyAMQgBXOk2wYqEOmSlMYUMgu7Qy+aN2wBzWDHz0MuHgFgAUKTJCuvQSPHLZ8xQBsa9Rrk5U/ADMqD242MgBPSSVpVU5uAFkASREvWgYYSytrAGIVYLpuAGUigVz8qkKyAEEmADcipISAEWsAAQAmAEZ2gAYyNq6eACUpORMeAGEIfAAHENUi1TrvXABuPoGh0bpxzKTdqErcGnXcqkCyErKrNv7BkbGqCYOMI4ZTngANAA4kDasOXoTAu50utQaTVat3u2yeL0Ox0+1Sg+ABQOkoOyVjo2BMuFm2FoVxCAGt+MIeAlZBxcNYAN7WMjMgYAZi2SBiuGwgW4hKgcmwHgGHRJ+CYqCZLMZVhZcrIpHIAB5cBJ8PhsFAIgA+KXyhW2AAKqkC0Hwfg4mqYAHdNfAibRQlBZMwrmxYOpFKg4MAqBgyHUYGB3eY9fLFWQlcRVerNTqw3KANoJGAYDgQJhJOYeAAUKbTGazsw8AHlZnIFOZqvpDDBcCdAwcvHRKvoyIQyPn05ns2WKwweNXa/WqIG+88qAAvNwKACUAF0EyzE0VLVBZhRsMBHrtnpkAFJ+gDi9FUNBzGAisxgEECOdw6YFs4XS+ZK7XG63O72PEPGBPhRHGAF5Xjed6BB4ECyM+i6yvqZDvpqn7bjsP5/gBZ7AZe163jmTCSMAoQwa+bIcgMKBuroSpCNqOZCAAVGQKi4HIuL9mgZAAGpBu6qDUdqZC4JIUC0LOZDWlwHoiCAMQari+jMCRMrwfKABCEQYDAeF1qxM50BxQkSCJMCzmsKlyiRSZdoW2Z5qm3ZFqW5buFWNawCOjZ0M2rbtp29k2cW46VoObl1g2MDjvgU56S+cHmWRbQUepml0YxzG6exXE8dAfE0YJwmiZZ0pFfqFxkCBOF3kIYkALw1awoG4cAGkmbOJXyjKORlRCjQtO1KllTmPXPEwPBJLgRQSLMszQJpTBtXF8XwcpS2rcN4o8EU7paTmzWafRYnpZUekcTm3HBjlKBKntMDamJOYQMAABWPFiYZxmmf18EAL65MCWKrXKv2LRZINLUUyVaUdbHuAZBUmQCq3fat7XJv5PbFnZBYY05/aucO4VNpUPkdtZONBQOQ7ueFkXRf2sWrYMnKJVckOpUxOnHZl528VdeXvYVYP6itgNkIN2FgXRtX1RLuG4Ddz5fcynXdfUvXQqLpWXENasjWNE1TTNArMAtmsdUr5nraNW26Dm943QdHMsVzsPlTzl0qjdd3lY9L3Bm98OfULgPAxiIKBBbwMqRbACqrxdEg2nOzDChw0ZomI0tyNLajZOOVjDm9s5wVU2Fo4wETLZ0G2pPo45FP49T5e09O9OwYzCfkWQce7An7PQydWUXVAuUCQLJntSLgPi41VXSw1lU5hID6zYrwcqSr4Jq1CFtyoNVv65N02zSbu/FevmsHzbsB28vj4YI7A+ZWd2Uj1dd+zd7D3Pa9+XpwjZ9mSh3+hHC++oo7wQtvHROT9XbjyDkjFGYCEJ51sqgwKxdKahQ8hXLyxNq6+XQbjFyIUCbN2clFVu7gGZLSZl3aB/dOYp30kPXm/E/4fUnhbGei9qpkDqgvSWK8nym01pvGo28+rIIGtrA+40j5GzmqIs2ytAHyivttO2wiH6HSYYPF+w8+LaK/r7X+8DM4qLIMAzEoCzYQP1LHV4rIOhJwynAwOFjzLZ3irnOuaC/EYLxqQpunlvIENrtjeumDG5lzHBQum1D260M7izHuGBnGMOToPd2b92HwK4dIlkPDJZ8IEbLO8EhKgYDXmbcRPUd6FK1uVORBtj7G3mmoqeljmQaNtkvKpj89HPxyXxSpuwTE/39hwjOajrHh0jiRKBuwMmwNTtMgByDvHmV8ZE/xuzAkkNLjgyuJM/L7OISXbBNN4lULnEk+KdCWZOJcQxJ2bi1kjL5mPQOBSzbFNwqUmWs8cxVJqWIsEEjIRSO6WLWRusNryMNifDpjTzaopUr0m+ILdiDKycM1+fEqkTL9tU9ZCDulzIBprex8pHG7FQK4l2azzHtS2dHZBaNzkFwChcrBZDQn4JrmcwuBzLn8oijcmK9zzKPIomkhlrzVksM+Xkn5yCulLX+XPfhQLF4SEgtXMFos6mSI1t0/e8LRqIraUozpai5SYp2vqhQ+hcXvJYQYthzrq7ErMR42Zf0bELODksjADKlVpw+p4lSbLIEcqIdy8m0TgmxNwWEoVRCG4ppwS3KV7VZVkFeAqtKQzXYqv5mq1aGr4paqljqwRuEDX6CNYDE1UKzWWItQ0PW1rFGn3RefGFDrLWbU0TmJtbqmUepVU231UyWUDqAYG+ZqKaWgzNkUVsoRGXMMjTMzZSDVqcpFbmTNyajmEzwVXDNATeUxJzZKtu+aUkUU3dXbdirS0fIJV8slvzNa1sBQ28CkFoLKNbRC+p0LzVwu7Qi1pfaUUwurSox1dsIJQR0W8qdp0VUYdkHO0lC6YWUtsdSxZqLmgEW3RGsl0afqHqWsenliaolBIveXE54ThU8qzRxuJ4wEl3OfczCiVGJCES0p+vFZaf2qv/uBje3DtblLrWU4F+EJNEUU0tNt6s1Fds3fBhRyKdPGvtSyNDeFqMwEnbut2cnNOScIwHBT9HRakeDeys2JY0yqB3YPYjWcdkntY0XdjVzONXtOWeiL4rc1PuQQW3zklMnuo4uW75Cn/2ixjgwHkmQADqRxNJ5aFFQfQhQmBKky7RWjC7WUkRpcDb6QA===)
(well I don't have a mobile sharplab)

@HurricanKai

**Comment by WhiteBlackGoose** [comment]
## To discuss

- [ ] `AllBitsSet` API for Simd and Scalar
- [ ] `MaxValueOver2` API for Simd and Scalar
- [ ] `IsHardwareAccelerated` should be `&& IsSupported`? Otherwise `Simd128<MyAwesomeType>.IsHardwareAccelerated` returns true on net5 on avx machine
- [ ] `Math.Abs` throws on `Math.Abs(int.MinValue)`. We can keep it, or we can have a faster version without this check

**Comment by HurricanKai** [comment]
Future: Look at checking for IsHardwareAccelerated before calling down into other methods, don't want to ie call Not(LessThen(...)) if it's not hardware accelerated, because it means two loops with non-hardware accelerated Loads/Stores

**Comment by HurricanKai** [comment]
Future: Improve IsNegative check by checking for bit instead of doing a full blown compare

**Comment by WhiteBlackGoose** [comment]
**Important**: [Notes from working group meeting](https://github.com/dotnet/Silk.NET/pull/690)
