### ISSUE TITLE
.NET 6 arm64 builds

### ISSUE THREAD

**Issue by Jomyy** [dotnet/Silk.NET#727]
yeah a native arm64 build would be nice i guess... i cant get it to work myself and i think it attract a wide audience imo

Tracking:

- [x] Assimp - OSX arm64
- [x] Assimp - Win arm64
- [x] Assimp - Linux arm64
- [ ] DXVK - Win arm64
- [ ] DXVK - Linux arm64
- [x] DirectStorage - Win arm64
- [x] GLFW - OSX arm64
- [x] GLFW - Win arm64 
- [x] GLFW - Linux arm64 
- [x] MoltenVK
- [x] OpenAL Soft - OSX arm64
- [x] OpenAL Soft - Win arm64
- [x] OpenAL Soft - Linux arm64
- [ ] ANGLE - OSX arm64
- [ ] ANGLE - Win arm64
- [ ] ANGLE - Linux arm64
- [x] SDL - OSX arm64
- [x] SDL - Win arm64
- [x] SDL - Linux arm64
- [x] SPIR-V Cross - Linux arm64
- [x] SPIR-V Cross - OSX arm64
- [x] SPIR-V Cross - Win arm64
- [x] SPIR-V Reflect - Linux arm64
- [x] SPIR-V Reflect - OSX arm64
- [x] SPIR-V Reflect - Win arm64 
- [x] Shaderc - Linux arm64
- [x] Shaderc - OSX arm64
- [x] Shaderc - Win arm64 
- [ ] Vkd3d - Linux arm64 
- [x] Vulkan Loader - OSX arm64
- [ ] Vulkan Loader - Win arm64
- [x] Vulkan Loader - Linux arm64
- [x] SwiftShader - OSX arm64
- [ ] SwiftShader - Win arm64
- [x] SwiftShader - Linux arm64
- [x] WGPU - OSX arm64
- [x] WGPU - Win arm64
- [x] WGPU - Linux arm64

**Comment by Perksey** [comment]
Community efforts have begun on doing this, starting with GLFW in PR #792. The February Update (v2.13.0) is likely to contain support for Apple Silicon, Linux TBC.

**Comment by roeyskoe** [comment]
Maybe this should stay open until everything is done?
Github does not fully understand what "partially resolves" means :D

**Comment by Perksey** [comment]
Agreed, that’s unfortunate - didn’t notice that! Reopening.

**Comment by Perksey** [comment]
@Beyley can this be closed?

**Comment by Beyley** [comment]
> @Beyley can this be closed?

unfortanately not yet, still missing osx-arm64 and linux-arm64 in a lot of places (ex. SDL) my PR only resolved the win-arm64 situation where feasable

**Comment by Perksey** [comment]
Added tracking to the issue description

**Comment by alexrp** [comment]
I think `Vulkan Loader - Win arm64` can be safely removed from the list. It does not look like it will support Windows Arm64 anytime soon, judging by https://github.com/KhronosGroup/Vulkan-Loader/issues/536 and a glance at the relevant code mentioned in that issue.

**Comment by alexrp** [comment]
Working on more platform coverage for native libraries in my branch: https://github.com/alexrp/Silk.NET/tree/natives

The goal is to cover `linux-arm`, `linux-arm64`, linux-x64`, `osx-arm64`, `osx-x64`, `win-arm64`, `win-x64`, and `win-x86` for all packages where it makes sense. I might consider doing musl-based RIDs in the future, but only if there's actual demand, as that looks to be quite a bit more effort.

Progress relative to upstream Silk.NET:

- Assimp
    - [x] `linux-arm`
    - [x] `linux-arm64`
    - [x] `win-arm64`
- DXVK
    - [ ] `linux-arm`
    - [ ] `linux-arm64`
    - [ ] `win-arm64`
- GLFW
    - [x] `linux-arm`
    - [x] `linux-arm64`
- OpenAL Soft
    - [x] `linux-arm`
    - [x] `linux-arm64`
    - [x] `linux-x64`
    - [x] `osx-arm64`
    - [x] `osx-x64`
    - [x] `win-arm64`
    - [x] `win-x64`
    - [x] `win-x86`
- SDL
    - [x] `linux-arm`
    - [x] `linux-arm64`
- Shaderc
    - [ ] `linux-arm`
- SPIRV-Cross
    - [ ] `linux-arm`
- SPIRV-Reflect
    - [ ] `linux-arm`
- SwiftShader
    - [ ] `linux-arm`
    - [ ] `linux-arm64`
    - [ ] `osx-arm64`
    - [ ] `win-arm64`
    - [ ] `win-x86`
- Vkd3d
    - [ ] `linux-arm`
    - [ ] `linux-arm64`
- Vulkan Loader
    - [x] `linux-arm`
    - [x] `linux-arm64`
    - [x] `osx-arm64`
    - [x] `win-arm64`
    - [x] `win-x86`
- wpu-native
    - [x] `linux-arm`
    - [x] `linux-arm64`

Not doing DXVK, Shaderc, SPIRV-Cross, SPIRV-Reflect, and Vkd3d until #1993 is merged. [Also, not doing ANGLE anytime soon.](https://github.com/dotnet/Silk.NET/blob/28b076373af3800011e9630b24306c1921bcecc8/build/nuke/Native/Angle.cs#L29)

**Comment by alexrp** [comment]
State of this issue once #2049 is merged:

* ANGLE for ~~Arm64~~ anything is blocked on #2024.
* DXVK for Arm64 is not done yet. Should be possible, but will require looking into [Meson's take on toolchain files](https://mesonbuild.com/Machine-files.html).
* SwiftShader for `win-arm64` is blocked on #2066.
* Vkd3d for Arm64 is not done yet. Should be possible with relatively little effort.
* Vulkan Loader for `win-arm64` is blocked on #2090.

**Comment by alexrp** [comment]
Reopening since #2049 only partially addressed this.

**Comment by Perksey** [comment]
My understanding that the shortfalls have superseding issues?

**Comment by alexrp** [comment]
We can do it that way too, sure. I just need to create an issue for the DXVK part, then it's all covered by separate issues.

**Comment by alexrp** [comment]
Updated https://github.com/dotnet/Silk.NET/issues/727#issuecomment-2054075091 with links to all remaining issues.
